#!/bin/bash

# count the number of directories and subdirectories (excluding the current and parent directories)
num_dirs=$(find . -mindepth 1 -maxdepth 1 -type d -name ".*" -o -type d -print | wc -l)

echo "Number of directories and subdirectories: $num_dirs"

